hibernate.driver_class = org.postgresql.Driver
hibernate.connection.url = jdbc:postgresql://localhost:5432/eventmanager_product_notifiedeo
hibernate.connection.username = fathurrahman.kesuma
hibernate.connection.password = Finalsmash!102938
hibernate.hbm2ddl.auto = update
hibernate.dialect = org.hibernate.dialect.PostgreSQL94Dialect
hibernate.show_sql = false